baseURL = "https://yourusername.github.io/notifuturo-site/"
languageCode = "es"
title = "Notifuturo"
pagerSize = 5
enableGitInfo = true
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
  defaultTheme = "light"
  disableSpecial1stPost = false
  disableScrollToTop = false
  disableAnchoredHeadings = false
  showPostNavLinks = true
  showCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Noticias"
    url = "/news/"
    weight = 2
  [[menu.main]]
    name = "Tecnología"
    url = "/tech/"
    weight = 3
  [[menu.main]]
    name = "Ciencia"
    url = "/science/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
